### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ShubhranshuSh** [IIT-M-Data-Science/Support#12]
### Name

Shubhranshu Sharma

### Student Email ID

21f3000591@student.onlinedegree.iitm.ac.in

### Additional Context

To explore more in the field of data science, Ai and ML through this community and will participate in various events and will contribute in those as well by giving my ideas and suggestions if require.

**Comment by blurrydev** [comment]
Invitation sent
