### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by tirth5828** [IIT-M-Data-Science/Support#20]
### Name

Tirth Joshi

### Student Email ID

21f1004286@student.onlinedegree.iitm.ac.in

### Additional Context

I am always ready to take on exciting and challenging projects. I would love to contribute to any projects in Web, android, Spark AR, and Machine Learning. Am even ready to learn new technologies, it's always fun!!!!

**Comment by blurrydev** [comment]
Invitation sent
